# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: devops-deployment
#   namespace: default
#   labels:
#     app: devops 
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: devops
#   template:
#     metadata:
#       labels:
#         app: devops
#     spec:
#       containers:
#       - name: devops-demo
#         image: armankhan2004/devops-demo:v20250701190148
#         ports:
#           - containerPort: 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  namespace: default
  labels:
    app: devops 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: devops-demo
          image: armankhan2004/devops-demo:v20250702004155
          ports:
            - containerPort: 80
